easy_admin:
  entities:
    Evenement:
      class: App\Entity\Evenement
      form:
        fields:
          - { property: "titre", label: "Titre" }
          - { property: "duree", label: "Durée" }
          - { property: "date", label: "Date" }
          - { property: "description", label: "Contenu" }
          - { property: "image",label: "Ajouter une image" }
          - { property: "categorie", label: "Catégorie" }
          - { property: "user_id", label: "Catégorie" }

      list:
        actions:
          - { name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-primary' }
          - { name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger' }
          
        fields:
          - { property: "titre", label: "Titre" }
          - { property: "duree", label: "Durée" }
          - { property: "date", label: "Date" }
          - { property: "description", label: "Contenu" }
          - { property: "image",label: "Ajouter une image" }
          - { property: "categorie", label: "Catégorie" }
          - { property: "user_id", label: "Créateur évènement" }